#!/bin/bash
# ^ just here for syntax highlighting 
# PowerMan2206's Sway keybind config file

# set the modifier key to Win
set $mod Mod4

# obvious, no?
bindsym --no-repeat $mod+Return exec foot

# stuff
bindsym --no-repeat $mod+q exec qutebrowser
bindsym --no-repeat $mod+t exec thunar
bindsym --no-repeat $mod+g exec gimp

# layout switcharoo
bindsym $mod+l exec swaymsg input type:keyboard xkb_switch_layout next

# little trolling
bindsym $mod+Shift+Space exec swaylock -u -i HDMI-A-1:~/walls/fake/beeg.png -i HDMI-A-2:~/walls/fake/smol.png

# bemenu stuff
bindsym --no-repeat $mod+d exec beemenu bemenu-run
# powermenu thing
bindsym --no-repeat $mod+Shift+e exec powermenu

# emoji stuff
bindsym --no-repeat $mod+m exec bemenu-emoji.sh

# to open youtube videos and shit in mpv
bindsym --no-repeat $mod+y exec mpv $(wl-paste)

# screenshot stuff
bindsym --no-repeat $mod+s exec screenshot area
bindsym --no-repeat $mod+Ctrl+s exec screenshot area swappy
bindsym --no-repeat $mod+Shift+s exec screenshot window
bindsym --no-repeat $mod+Ctrl+Shift+s exec screenshot window swappy
bindsym --no-repeat $mod+r exec color-select



### nerd shit

# pactl to control pulseaudio volume with an XF86 keyboard
bindsym XF86AudioRaiseVolume exec pamixer -i 5
bindsym XF86AudioLowerVolume exec pamixer -d 5
bindsym --no-repeat XF86AudioMute exec pamixer -t

# above but for mpd control
bindsym --no-repeat XF86AudioPlay exec mpc toggle
bindsym XF86AudioNext exec mpc next
bindsym XF86AudioPrev exec mpc prev

# drag floating windows
floating_modifier $mod
# fullscreen the focused container
bindsym --no-repeat $mod+f fullscreen toggle
# toggle tiling/floating
bindsym --no-repeat $mod+Space floating toggle
# kill focused window
bindsym --no-repeat $mod+Shift+q kill
bindsym --no-repeat Mod1+f4 kill # hehe

# change focus
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
# move focused window
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in a horizontal and vertical orientation
# ok I made it my own kinda
bindsym $mod+v split h
bindsym $mod+c split v
# toggle split
bindsym --no-repeat $mod+e layout toggle split

# reload the configuration file
bindsym $mod+Shift+c reload

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused workspace
bindsym $mod+Shift+1 move workspace $ws1
bindsym $mod+Shift+2 move workspace $ws2
bindsym $mod+Shift+3 move workspace $ws3
bindsym $mod+Shift+4 move workspace $ws4
bindsym $mod+Shift+5 move workspace $ws5
bindsym $mod+Shift+6 move workspace $ws6
bindsym $mod+Shift+7 move workspace $ws7
bindsym $mod+Shift+8 move workspace $ws8
bindsym $mod+Shift+9 move workspace $ws9
bindsym $mod+Shift+0 move workspace $ws10
