#!/bin/bash
# ^ just here for syntax highlighting 

# PowerMan2206's Sway config file

# sets the workspace names (numbers)
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# yoink the binds
include $HOME/.config/sway/binds

default_border pixel 1 #titlebars are cringe

# gaps pog
gaps outer 0
gaps inner 3

# lock screen
exec swayidle -w timeout 900 'swaylock-fancy -g' #grayscale lockscreen without text

# arrange monitors correctly and set wallpapers
output "Dell Inc. DELL S2316H RYCGX5CL0RWT" pos 0 0 bg ~/walls/sweet_arch_1080p.png stretch
output "Samsung Electric Company SyncMaster H9XQ206649" pos 1920 80 bg ~/walls/sweet_tux_1080p.png fill

# make the mouse not suck ass
input 1133:49291:Logitech_G502_HERO_SE accel_profile flat
input 1133:49291:Logitech_G502_HERO_SE pointer_accel -0.966
# use correct cursor, idk if it actually works
seat seat0 xcursor_theme win8

# change keyboard rate thing
input 2385:5842:Kingston_HyperX_Alloy_FPS_Pro_Mechanical_Gaming_Keyboard repeat_delay 300
input 2385:5842:Kingston_HyperX_Alloy_FPS_Pro_Mechanical_Gaming_Keyboard repeat_rate 30

# autostart 
exec mako #notifications
exec ~/.config/waybar/launch.sh #bar
exec discord-canary #discord
exec lxpolkit #polkit thing

# make some windows always float
for_window [app_id="pavucontrol"] floating enable
