#!/bin/bash
# ^ just here for syntax highlighting 

# PowerMan2206's Sway config file

# gaps and no titlebars 
default_border pixel 2
gaps inner 3
gaps outer 0

# sets the workspace names (numbers)
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# yoink the binds
include $HOME/.config/sway/binds

# make some windows do special stuff
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="blueberry"] floating enable
for_window [class="discord"] move workspace $ws2
for_window [app_id="weechat"] move workspace $ws2

# autostart 
exec remind $HOME/.config/remind/reminders.rem #i don't rember 😔
exec ~/.config/waybar/launch.sh #bar
exec lxpolkit #polkit thing 
exec mako #notifications
exec discord-canary
exec "alacritty --class weechat -e weechat"
exec thunar --daemon #running it from a terminal leaves the terminal usable
exec gammastep -O 3500

# we do a
exec swayidle -w timeout 900 'swaylock -u -i HDMI-A-1:~/walls/fake/beeg.png -i HDMI-A-2:~/walls/fake/smol.png' #fake Windows lol

# arrange monitors correctly and set wallpapers
output "Dell Inc. DELL S2316H RYCGX5CL0RWT" pos 0 0 bg ~/walls/sweet_arch_1080p.png stretch
output "Samsung Electric Company SyncMaster H9XQ206649" pos 1920 80 bg ~/walls/sweet_tux_1080p.png fill

# make the mouse not suck ass
input 1133:49291:Logitech_G502_HERO_SE accel_profile flat
input 1133:49291:Logitech_G502_HERO_SE pointer_accel -0.935

# change keyboard things
input 2385:5842:Kingston_HyperX_Alloy_FPS_Pro_Mechanical_Gaming_Keyboard repeat_delay 300
input 2385:5842:Kingston_HyperX_Alloy_FPS_Pro_Mechanical_Gaming_Keyboard repeat_rate 30
input 2385:5842:Kingston_HyperX_Alloy_FPS_Pro_Mechanical_Gaming_Keyboard xkb_layout us,hr
