#!/bin/bash
# ^ just here for syntax highlighting 
# PowerMan2206's i3 keybind config file

# set the modifier key to Win
set $mod Mod4

# obvious, no?
bindsym $mod+Return exec --no-startup-id alacritty

bindsym $mod+q exec --no-startup-id firefox
bindsym $mod+t exec --no-startup-id thunar
bindsym $mod+g exec --no-startup-id gimp
bindsym $mod+d exec --no-startup-id "dmenu_run -i -l 20 -nb '#181b28' -nf '#e8e7e4' -sb '#181b28' -sf '#ef2f27'"

# lauch the logout menu thing
bindsym $mod+Shift+e exec --no-startup-id powermenu
# also lockscreen
bindsym $mod+l exec --no-startup-id "i3lock -c 181b28"

# using `changer` script because of xob
# control volume with keybinds
bindsym XF86AudioRaiseVolume exec --no-startup-id changer volume -i
bindsym XF86AudioLowerVolume exec --no-startup-id changer volume -d
bindsym XF86AudioMute        exec --no-startup-id pamixer -t
bindsym XF86AudioMicMute     exec --no-startup-id pamixer --source "alsa_input.pci-0000_34_00.6.analog-stereo" pamixer -t
# same for screen brightness
bindsym XF86MonBrightnessUp   exec --no-startup-id changer brightness +5% 
bindsym XF86MonBrightnessDown exec --no-startup-id changer brightness 5%- 

# mpd control with keybinds
bindsym XF86AudioPlay exec --no-startup-id mpc toggle
bindsym XF86AudioNext exec --no-startup-id mpc next
bindsym XF86AudioPrev exec --no-startup-id mpc prev
# same as the above volume control but with LAlt
bindsym Mod1+XF86AudioRaiseVolume exec --no-startup-id changer mpd +5
bindsym Mod1+XF86AudioLowerVolume exec --no-startup-id changer mpd -5

# screenshot stuff
bindsym $mod+s exec --no-startup-id screenshot

# color select stuff
bindsym $mod+r exec --no-startup-id color-select


## nerd shit

# change focus
bindsym $mod+Left  focus left
bindsym $mod+Down  focus down
bindsym $mod+Up    focus up
bindsym $mod+Right focus right

# move focused window
# 20px for floating
bindsym $mod+Shift+Left  move left  20 px
bindsym $mod+Shift+Down  move down  20 px
bindsym $mod+Shift+Up    move up    20 px
bindsym $mod+Shift+Right move right 20 px

# resize windows
# makes it so that it's "relative" to what window you're focused on
# works well enough for 4 windows, one in each corner
bindsym $mod+Ctrl+Left  resize grow left  20 px; resize shrink right 20 px
bindsym $mod+Ctrl+Down  resize grow down  20 px; resize shrink up    20 px
bindsym $mod+Ctrl+Up    resize grow up    20 px; resize shrink down  20 px
bindsym $mod+Ctrl+Right resize grow right 20 px; resize shrink left  20 px


# drag floating windows (and swap them if one is dropped on another with Shift)
floating_modifier $mod
tiling_drag swap_modifier Shift
# fullscreen the focused container
bindsym $mod+f fullscreen toggle
# toggle tiling/floating
bindsym $mod+space floating toggle
# kill focused window
bindsym $mod+Shift+q kill
bindsym --whole-window $mod+button2 kill

# split in a horizontal and vertical orientation
# ok I made it my own kinda
bindsym $mod+v split h
bindsym $mod+c split v
# toggle split
bindsym $mod+e layout toggle split

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3
bindsym $mod+Shift+r restart

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused workspace
bindsym $mod+Shift+1 move workspace $ws1
bindsym $mod+Shift+2 move workspace $ws2
bindsym $mod+Shift+3 move workspace $ws3
bindsym $mod+Shift+4 move workspace $ws4
bindsym $mod+Shift+5 move workspace $ws5
bindsym $mod+Shift+6 move workspace $ws6
bindsym $mod+Shift+7 move workspace $ws7
bindsym $mod+Shift+8 move workspace $ws8
bindsym $mod+Shift+9 move workspace $ws9
bindsym $mod+Shift+0 move workspace $ws10
