#!/bin/bash
# just here for syntax highlighting

# PowerMan2206's i3 config file

# sets the workspace names (numbers)
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# source binds
include $HOME/.config/i3/binds

# gaps and no titlebars
default_border pixel 3
gaps inner 5
gaps outer 0

# make some windows do special stuff
for_window [class="pavucontrol"] floating enable
for_window [class="discord"] move workspace $ws2

# stuff that's gotta be launched
exec --no-startup-id remind $HOME/.config/reminders.rem # i don't rember 😔
exec --no-startup-id battery-watcher.sh # shit works
exec --no-startup-id picom
exec --no-startup-id dunst
exec --no-startup-id discord
exec --no-startup-id $HOME/.config/polybar/launch.sh
exec --no-startup-id $HOME/.config/xob/launch.sh
exec --no-startup-id nm-applet
exec --no-startup-id redshift -PO 4000k
exec --no-startup-id thunar --daemon # running it from a terminal leaves the terminal usable
exec --no-startup-id tldr -u # I always forget so

# also 2nd monitor and stuff
exec --no-startup-id "xrandr --output HDMI-1-1 --auto --above eDP"
exec --no-startup-id "nitrogen --restore"

# keyboard repetition thingy that I prefer
exec_always --no-startup-id xset r rate 250 40
# exec_always because for some reason sometimes it
# stops working, so this is a fast way to reapply it

# so that mouse doesn't follow focus
# (but focus still follows mouse, different thing)
mouse_warping none

# lockscreen thing
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock -c 181b28 --nofork
