#!/bin/bash
# thanks to sorpigal for basically rewriting a part of this to use declare

# CONFIGURATION (because I'm too lazy to make it automatic)
#
# 1. edit the sink variables below
# 2. put your main sink and its nickname into the sink1 array below
# 3. same for your other sink
# 4. somethingsomething, you'll figure it out, do what I did
# 5. restart Waybar with the launch.sh script
# 6. pray it works

# vars and stuff
config="$HOME/.config/waybar/scripts/pipewire-config"
. "$config"

# here and not in the config file beceuase for some reason 
# they get deleted if the volume is adjusted too fast (idk either)
sink1=("alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo-output" "Headphones ")
sink2=("alsa_output.pci-0000_09_00.1.hdmi-stereo-extra1" "Speakers 蓼")

# do function stuff
waybarstuff () {
	# put the actual output onto the bar
	. "$config"
	echo "$volume% $nick $mute"
}

nextsink () {
	# you get the point, just scrolls through them
	case "$sink" in
		"${sink1[0]}" )
			sink="${sink2[0]}"
			nick="${sink2[1]}"
			;;
			
		"${sink2[0]}" ) 
			sink="${sink1[0]}"
			nick="${sink1[1]}"
			;;
	esac

	pactl set-default-sink "$sink"
	echo "sink set to: $sink ($nick)"
}

setmute () {
	# set the mute variable
	case $(pamixer --get-mute) in
		true ) mute='(muted)' ;;
		false ) mute= ;;
	esac
}

# yes aliases as well because fuck you
shopt -s expand_aliases # make aliases work
alias declare-stuff='declare -p sink1 sink2 sink nick volume mute > "$config"'
alias setvolume='volume=$(pamixer --get-volume)'

# --------------------------------------------------
# actual code starts here

setmute
setvolume

# check if sink variable is empty and if it is, default to the first sink 
# (for some reason it nukes itself sometimes)
case "$sink" in
	"" )
		sink="${sink1[0]}"
		nick="${sink1[1]}"
		declare-stuff
		;;
	* ) declare-stuff
esac

pactl set-default-sink "$sink"

while getopts "cmi:d:" arg; do
	case "$arg" in
		c )
			nextsink
			setmute
			setvolume
			declare-stuff
			exit
			;;
		
		m )
			pamixer -t
			setmute
			declare-stuff
			exit
			;;
		
		i )
			pamixer -i "$OPTARG"
			setvolume
			declare-stuff
			exit
			;;
		d )
			pamixer -d "$OPTARG"
			setvolume
			declare-stuff
			exit
			;;
		* ) echo cringe; exit ;;
	esac
done

waybarstuff

while inotifywait -qq -e modify "$config"; do waybarstuff; done
